### PR TITLE
add phpunit config

### PR DESCRIPTION
**Pull request by abacaphiliac**
add phpunit config with a whitelist so that coverage reports can be generated in CI.

what do you think?

### CODE REVIEW

**Comment by drichelson** [comment]
I changed the base branch to one in our repo to see what happens on CircleCI..

**Comment by drichelson** [comment]
@abacaphiliac It looks like this [runs](https://circleci.com/gh/launchdarkly/php-client/140#artifacts/containers/0) without errors in CircleCI, but doesn't do anything. Check out the [CircleCI docs](https://circleci.com/docs/language-php/) for more info

**Comment by abacaphiliac** [comment]
ah, it seems xdebug isn't enabled on the build image.

the circle ci docs tell me that it is enabled on their 14.04 image, and how to disable xdebug if we need a performance boost (e.g. for composer): https://circleci.com/docs/language-php/#xdebug

do you know which build image we're using? maybe the specificity of `5.5.21` is forcing a particular image without xdebug enabled.

this is the output we're looking for:
```
16:32 $ vendor/bin/phpunit --coverage-text
PHPUnit 4.8.26 by Sebastian Bergmann and contributors.

.........................

Time: 918 ms, Memory: 13.50MB

OK (25 tests, 58 assertions)


Code Coverage Report:      
  2016-12-23 23:32:07      
                           
 Summary:                  
  Classes:  5.26% (1/19)   
  Methods: 42.48% (48/113) 
  Lines:   42.51% (281/661)

\LaunchDarkly::Clause
  Methods:  22.22% ( 2/ 9)   Lines:  23.33% (  7/ 30)
\LaunchDarkly::EventProcessor
  Methods:  57.14% ( 4/ 7)   Lines:  71.74% ( 33/ 46)
\LaunchDarkly::FeatureFlag
  Methods:  25.00% ( 3/12)   Lines:  29.55% ( 26/ 88)
\LaunchDarkly::GuzzleFeatureRequester
  Methods:  33.33% ( 1/ 3)   Lines:  40.62% ( 13/ 32)
\LaunchDarkly::LDClient
  Methods:  20.00% ( 2/10)   Lines:  46.02% ( 52/113)
\LaunchDarkly::LDUser
  Methods:  80.00% (12/15)   Lines:  63.95% ( 55/ 86)
\LaunchDarkly::LDUserBuilder
  Methods:  91.67% (11/12)   Lines:  91.30% ( 21/ 23)
\LaunchDarkly::Operators
  Methods:   0.00% ( 0/ 2)   Lines:  39.71% ( 27/ 68)
\LaunchDarkly::Prerequisite
  Methods:   0.00% ( 0/ 4)   Lines:  14.29% (  1/  7)
\LaunchDarkly::Rollout
  Methods:  50.00% ( 2/ 4)   Lines:  77.78% (  7/  9)
\LaunchDarkly::Rule
  Methods:  50.00% ( 2/ 4)   Lines:  57.14% (  8/ 14)
\LaunchDarkly::Target
  Methods:  50.00% ( 2/ 4)   Lines:  71.43% (  5/  7)
\LaunchDarkly::Util
  Methods: 100.00% ( 3/ 3)   Lines: 100.00% ( 14/ 14)
\LaunchDarkly::VariationOrRollout
  Methods:  33.33% ( 2/ 6)   Lines:  19.44% (  7/ 36)
\LaunchDarkly::WeightedVariation
  Methods:  50.00% ( 2/ 4)   Lines:  71.43% (  5/  7)
```

**Comment by abacaphiliac** [comment]
ah, the build output (thanks for the link) says we're using `CIRCLE_BUILD_IMAGE=ubuntu-12.04`

**Comment by drichelson** [comment]
I made a few changes, so it works now: https://circleci.com/gh/launchdarkly/php-client/143

I'm fine with merging this, but keep in mind that our testing strategy here at LaunchDarkly often means these tests will have lower coverage than is desired. This is because we have regularly running integration tests that assert the same exact behavior across all SDKs as described [here](https://github.com/launchdarkly/python-client/blob/master/README.md#testing)

**Comment by abacaphiliac** [comment]
@drichelson that's great news! good job. mind if i ask what you had to change?

i completely understand about the coverage and the test strategy. if i can get the integration tests running in CI as well then perhaps we can run the entire suite together. for a more complete picture.

**Comment by drichelson** [comment]
I changed the build image to Ubuntu 14 (one of the few CircleCI settings avaialble in the web ui), specified the php version, and renamed the phpunit.xml.dist to phpunit.xml

**Pull request merged**
