### PR TITLE
Fixes #67

### LINKED ISSUE #67: Warning: json_decode() expects parameter 1 to be string, array given
### Steps to reproduce

- Using `LDDFeatureRequester` try to fetch all flags by a user:
```php
$client = new LDClient(
    '...key',
    ['feature_requester_class' => 'LaunchDarkly\LDDFeatureRequester', ...]
);
$user = new LDUser(...);
$client->allFlags($user);
```

### Warning

- `Warning: json_decode() expects parameter 1 to be string, array given`

### Analysis

- [Here](https://github.com/launchdarkly/php-client/blob/master/src/LaunchDarkly/LDDFeatureRequester.php#L97) it's using predis' `hgetall()`. This method returns an `array`;
- [Here](https://github.com/launchdarkly/php-client/blob/master/src/LaunchDarkly/LDDFeatureRequester.php#L99) the SDK is trying to decode `$raw`, but `$raw` is an `array` not a `string`.

### Propose

- Iterate the array and decode only it's rows;

### PR DESCRIPTION
**Pull request by tiagobutzke**
Fixes https://github.com/launchdarkly/php-client/issues/67

### CODE REVIEW

**Comment by arun251** [comment]
Thanks for the fix, including some good unit tests!

**Comment by tiagobutzke** [comment]
@arun251 you're welcome. Do you know when we're going to have a new release with this fix?

**Comment by arun251** [comment]
@tiagobutzke I've released 2.0.7 with this fix.

**Comment by tiagobutzke** [comment]
Thank you @arun251

**Pull request merged**
