### PR TITLE
Check feature requester passed in options has the required interface

### PR DESCRIPTION
**Pull request by richardmiller**

### CODE REVIEW

**Comment by jkodumal** [comment]
This should pass CI after merging master back into this branch.

**Comment by jkodumal** [comment]
@richardmiller would you mind merging back master and updating this PR? That should make it fairly trivial to merge this.

**Comment by richardmiller** [comment]
@jkodumal got there in the end :) Had to downgrade phpunit back to 4.8 as version 5 onwards requires php >= 5.6

**Comment by jkodumal** [comment]
Thanks! LGTM.

**Pull request merged**
