### PR TITLE
Fix: Declare a single class per file

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] declares a single class per file

💁‍♂️ For reference, see https://www.php-fig.org/psr/psr-1/#3-namespace-and-class-names.

### CODE REVIEW

**Comment by eli-darkly** [comment]
I understand that this is a common convention, but is having multiple classes in a file actually causing any problems? Everything you've broken out is for internal use only, and we find it easier to keep track of closely related logic by grouping it together.

**Comment by localheinz** [comment]
@eli-darkly 

If multiple classes are declared per file, it might become impossible to autoload a class with a PSR-0- or PSR-4-autoloader, as both of them resolve paths to the files containing them from the class name. 

As an alternative to declaring multiple classes per file to prevent external usage, or, let’s say, to indicate that they are only intended for internal use, classes could also be annotated with `@internal`, see http://docs.phpdoc.org/references/phpdoc/tags/internal.html. 

Closely related classes could also be grouped in namespaces, although that would be a backwards-incompatible change, and should probably be postponed for a later point in time, for example, when also dropping support for unsupported PHP versions. 

What do you think?

**Comment by eli-darkly** [comment]
Sorry for the delay. Yes, let's do this.

**Comment by localheinz** [comment]
Thank you, @eli-darkly!

**Pull request merged**
