### PR TITLE
Allow the patch version of psr/log to be dynamic with minimum patch 0

### LINKED ISSUE #60: 2.0.0 requires psr/log 1.0.0 explicitly
`master` is versioned to psr/log version `1.0.*` however v2 (including 2.0.0 and 2.0.1) is versioned explicitly to psr/log version `1.0.0`

### PR DESCRIPTION
**Pull request by bradynpoulsen**
Fixes #60

### CODE REVIEW

**Comment by bradynpoulsen** [comment]
I would like to propose this to be considered in version 2.0.2

**Comment by drichelson** [comment]
Hi @bradynpoulsen Thanks for the PR!
The v2 branch is no longer in use. We're releasing from master, so do you mind retargeting to master?

**Comment by bradynpoulsen** [comment]
Okay! I will rebase

**Comment by bradynpoulsen** [comment]
@drichelson It looks like this was fixed by 2.0.4 but it wasn't pulled in by composer for some reason hmm

**Pull request closed without merging**
